application: simple-signaling
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_dir: doc

- url: /
  static_files: doc/index.html
  upload: doc/index.html

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^([^doc]).*$
