name: twilio-conversations-js
targets:
  - cent6
build:
  dependencies:
    - node
    - zip
    - pandoc
  commands:
    - make clean
    - make
    - rm -rf sdk
    - mv build/sdk .
contents:
  include:
    - sdk
install:
  prefix: /mnt
