application: simple-signaling
version: 2
runtime: python27
api_version: 1
threadsafe: yes

# index files
handlers:
- url: /(.+)/
  static_files: \1/index.html
  upload: (.+)/index.html

# site root
- url: /
  static_files: index.html
  upload: index.html

# For folders without trailing slashes - ideally a 301 redirect
- url: /([^\.]+)([^/])
  static_files: \1\2/index.html
  upload: (.+)/index.html

# Redirect Everything else
- url: /(.+)
  static_files: \1
  upload: (.+)

# skip_files:
# - ^(.*/)?#.*#$
# - ^(.*/)?.*~$
# - ^(.*/)?.*\.py[co]$
# - ^(.*/)?.*/RCS/.*$
# - ^(.*/)?\..*$
# - ^([^doc]).*$
