application: simple-signaling
version: 4
runtime: python27
api_version: 1
threadsafe: true

env_variables:
  twilio_allowed_realms: dev,stage,prod
  twilio_default_realm: prod

handlers:
- url: /css/bootstrap.min.css
  static_files: css/bootstrap.min.css
  upload: css/bootstrap.min.css

- url: /img/twilio41x41.png
  static_files: img/twilio41x41.png
  upload: img/twilio41x41.png

- url: /img/twilio41x41gray.png
  static_files: img/twilio41x41gray.png
  upload: img/twilio41x41gray.png

- url: /
  script: main.app

- url: /config
  script: main.app

- url: /doc
  script: main.app

- url: /doc/(.*)
  script: main.app

- url: /index.html
  script: main.app

- url: /js/index.js
  script: main.app

- url: /js/twilio-signal.js
  script: main.app

- url: /token
  script: main.app

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- twilio_credentials.json.example
- venv
